Fail("ERROR", "Cause message")
    result: '$'
