Fail("ERROR", "Cause message")
    output: '$'
